### ISSUE TITLE
UnixSocket transport is not available on MacOS

### ISSUE THREAD

**Issue by kriomant** [sp1ff/syslog-tracing#1]
But in fact `std::os::unix::net` is available on MacOS.

You use `#[cfg(target_os="linux")]` for related code, I propose to use `#cfg(target_family="unix")]` (or `#[cfg(unix)]` which is shortcut).

**Comment by kriomant** [comment]
BTW `std::os::unix::net::{UnixDatagram, UnixStream}` are already imported unconditionally, so crate just won't compile for non-unix.

**Comment by sp1ff** [comment]
You are absolutely correct, @kriomant. I don't have access to a MacOS machine for development or testing, and I chose to just not compile on Mac. Care to submit a patch?

**Comment by kriomant** [comment]
https://github.com/sp1ff/syslog-tracing/pull/2

**Comment by sp1ff** [comment]
merged-- tyvm
