### ISSUE TITLE
Cannot configure layers

### ISSUE THREAD

**Issue by ltabis** [sp1ff/syslog-tracing#3]
I believe `tracing_rfc_5424::layer::Layer` cannot be customized with the [tracing_rfc_5424::rfc5424::Rfc5424Builder](https://docs.rs/tracing-rfc-5424/0.1.0/tracing_rfc_5424/rfc5424/struct.Rfc5424.html#method.builder).
The struct  [tracing_rfc_5424::rfc5424::Rfc5424Builder](https://docs.rs/tracing-rfc-5424/0.1.0/tracing_rfc_5424/rfc5424/struct.Rfc5424.html#method.builder) cannot be used anywhere because the layer constructors only generate a default instance of the `syslog_formatter` parameter (it is also private to the layer struct, so it cannot be changed by accessing the parameter)

Am I missing something ?

**Comment by sp1ff** [comment]
Not sure off the top of my head-- let me take a look...

**Comment by ltabis** [comment]
I made a [fork](https://github.com/viridIT/syslog-tracing) if that can help you !

**Comment by sp1ff** [comment]
If you've got a PR, I'd love to take a look!

**Comment by ltabis** [comment]
I've opened one [here](https://github.com/sp1ff/syslog-tracing/pull/4). I've only added a function that enables you to pass the `Rfc5424` formatter as parameter, it's not really flexible :p

**Comment by ltabis** [comment]
A good implementation would let you configure the other RFC as well, but I wasn't sure what would be best.

**Comment by sp1ff** [comment]
No, you didn't miss anything. This crate is in its early days, and I've only added constructors as I've needed them. Thanks for the patch-- it's merged!
