### ISSUE TITLE
What is the license ?

### ISSUE THREAD

**Issue by avandecreme** [sp1ff/syslog-tracing#9]
There is no license file in this repo.

On crates.io, it says GPL 3.0.

Can you confirm and maybe add a license file in this repo?

**Comment by sp1ff** [comment]
It is indeed GPL 3.0. I've added the license to the project, albeit under the name `COPYING` (I generally try to adhere the GNU [coding standards](https://www.gnu.org/prep/standards/standards.html#Releases)). Is the name `LICENSE` significant in some way? Please re-open if so.
